### ISSUE TITLE
[catcollar] io_uring fails on bare metal

### ISSUE THREAD

**Issue by iyzhang** [demikernel/demikernel#432] opened 2023-01-19 03:17 UTC
## Description

All system tests for catcollar on bare metal fail right now.

## How to Reproduce

1. Run this command on the server side: `make test-system-rust LIBOS=catcollar TEST=udp-ping-pong RUST_BACKTRACE=full CONFIG_PATH=/demikernel/config.yaml ARGS='--server 198.19.200.1:12345 198.19.200.2:23456'`
2. Run this command on the client side: `make test-system-rust LIBOS=catcollar TEST=udp-ping-pong RUST_BACKTRACE=full CONFIG_PATH=/demikernel/config.yaml ARGS='--client 198.19.200.2:23456 198.19.200.1:12345'`

Same issue occurs with this run of the azure tables script:
`python3 ../tools/azure_tables.py --server prometheus1 --client prometheus2 --server-addr 198.19.200.1 --client-addr 198.19.200.2 --test-system --libos catcollar --branch dev --repository /demikernel/testing/demikernel --config-path /demikernel/config.yaml --connection-string XXX --table-name prometheus`

## Logs

Server side output
```
timeout 30 /demikernel/testing/demikernel/bin/examples/rust/udp-ping-pong.elf --server 198.19.200.1:12345 198.19.200.2:23456
thread 'main' panicked at 'unexpected result', examples/rust/udp-ping-pong.rs:108:18
stack backtrace:
   0:     0x55e7bfbc38ac - std::backtrace_rs::backtrace::libunwind::trace::h58c649c53097142b
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e7bfbc38ac - std::backtrace_rs::backtrace::trace_unsynchronized::h8a2218341115550a
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e7bfbc38ac - std::sys_common::backtrace::_print_fmt::hea4b2f7f6d570ca4
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55e7bfbc38ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d8d34f4e85c6a60
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55e7bfb0e32e - core::fmt::write::haf2065fc0d3659f4
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/fmt/mod.rs:1208:17
   5:     0x55e7bfb9d454 - std::io::Write::write_fmt::h6dce18c304ee54a2
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/io/mod.rs:1682:15
   6:     0x55e7bfbc4c1f - std::sys_common::backtrace::_print::hec602170f4d3e048
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55e7bfbc4c1f - std::sys_common::backtrace::print::h8aa4a47604c83c88
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55e7bfbc481f - std::panicking::default_hook::{{closure}}::h68a2f001ac3644c4
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs:267:22
   9:     0x55e7bfbc58a2 - std::panicking::default_hook::h4861c4cf633cd613
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs:286:9
  10:     0x55e7bfbc58a2 - std::panicking::rust_panic_with_hook::h404216ffd42d1a9f
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs:688:13
  11:     0x55e7bfbc5354 - std::panicking::begin_panic_handler::{{closure}}::hbfc6e95ed3b74164
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs:577:13
  12:     0x55e7bfbc52ec - std::sys_common::backtrace::__rust_end_short_backtrace::h6c2b4fdde46f911c
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55e7bfbc52c1 - rust_begin_unwind
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs:575:5
  14:     0x55e7bfadf942 - core::panicking::panic_fmt::h52720972d063b41a
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/panicking.rs:64:14
  15:     0x55e7bfaee582 - udp_ping_pong::server::ha55bcdf0478ac87a
  16:     0x55e7bfaefcd7 - udp_ping_pong::main::h307e3c989b15437d
  17:     0x55e7bfaed333 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6dae13834e29fd51
  18:     0x55e7bfaf0297 - main
  19:     0x7faab0667083 - __libc_start_main
                               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  20:     0x55e7bfaed26e - _start
  21:                0x0 - <unknown>
timeout: the monitored command dumped core
make: *** [linux.mk:185: test-system-rust] Aborted
```

Client side output
```
timeout 30 /demikernel/testing/demikernel/bin/examples/rust/udp-ping-pong.elf --client 198.19.200.2:23456 198.19.200.1:12345
thread 'main' panicked at 'unexpected operation result', examples/rust/udp-ping-pong.rs:223:18
stack backtrace:
   0:     0x557cae2068ac - std::backtrace_rs::backtrace::libunwind::trace::h58c649c53097142b
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557cae2068ac - std::backtrace_rs::backtrace::trace_unsynchronized::h8a2218341115550a
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557cae2068ac - std::sys_common::backtrace::_print_fmt::hea4b2f7f6d570ca4
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x557cae2068ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d8d34f4e85c6a60
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x557cae15132e - core::fmt::write::haf2065fc0d3659f4
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/fmt/mod.rs:1208:17
   5:     0x557cae1e0454 - std::io::Write::write_fmt::h6dce18c304ee54a2
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/io/mod.rs:1682:15
   6:     0x557cae207c1f - std::sys_common::backtrace::_print::hec602170f4d3e048
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x557cae207c1f - std::sys_common::backtrace::print::h8aa4a47604c83c88
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x557cae20781f - std::panicking::default_hook::{{closure}}::h68a2f001ac3644c4
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs:267:22
   9:     0x557cae2088a2 - std::panicking::default_hook::h4861c4cf633cd613
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs:286:9
  10:     0x557cae2088a2 - std::panicking::rust_panic_with_hook::h404216ffd42d1a9f
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs:688:13
  11:     0x557cae208354 - std::panicking::begin_panic_handler::{{closure}}::hbfc6e95ed3b74164
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs:577:13
  12:     0x557cae2082ec - std::sys_common::backtrace::__rust_end_short_backtrace::h6c2b4fdde46f911c
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x557cae2082c1 - rust_begin_unwind
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs:575:5
  14:     0x557cae122942 - core::panicking::panic_fmt::h52720972d063b41a
                               at /rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/panicking.rs:64:14
  15:     0x557cae1329c7 - udp_ping_pong::main::h307e3c989b15437d
  16:     0x557cae130333 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6dae13834e29fd51
  17:     0x557cae133297 - main
  18:     0x7f07b3868083 - __libc_start_main
                               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  19:     0x557cae13026e - _start
  20:                0x0 - <unknown>
timeout: the monitored command dumped core
make: *** [linux.mk:185: test-system-rust] Aborted
```

## Expected Behavior

Passed tests with no errors

**Comment by ppenna** [comment] 2023-01-19 11:08
@iyzhang

- I do confirm the issue on a Baremetal deployment
- I DO NOT confirm the issue on a Azure VM deployment

From this conclusions I believe that the issue is related to OS environment on the Baremetal deployment.

I am now investigating what the causes may be.

**Comment by iyzhang** [comment] 2023-01-19 18:22
I tested the PR and it fixed the issue.

**Comment by ppenna** [comment] 2023-01-19 19:06
I'm opening up the issue because it is still not merged in.

**Closed** 2023-01-20 01:44 UTC
Labels: bug, confirmed, baremetal, azure
